site_name: Surfing
repo_url: https://github.com/MoGuangYu/Surfing
repo_name: MoGuangYu/Surfing
copyright: Copyright &copy 2024 Surfing
edit_uri: "https://github.com/MoGuangYu/Meta-Duocs/blob/main/docs/"
dev_addr: "127.0.0.1:11451"
extra:
  generator: false
  analytics:
    provider: google
    property: G-1BJ0XH0RSM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MoGuangYu/Surfing
    - icon: material/file-document
      link: https://github.com/MoGuangYu/Meta-Docs

theme:
  name: material
  logo: assets/images.jpeg
  favicon: assets/images.jpeg
  features:
    - search.highlight
    - navigation.tracking
    - navigation.instant
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
   # - content.action.edit
    - content.code.copy
    - content.code.select
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3
      anchorlink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

plugins:
  - search
  - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: zh
          name: 简体中文
        - build: true
          default: false
          locale: en
          name: English
          site_name: "mihomo docs"
          nav_translations:
            简介: Introduction


  - git-revision-date-localized:
      locale: zh

nav:
  - 简介: index.md
  - Tips：config/Tips.md
